[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
madvise = { version = "0.1.0" }
memmap = { version = "0.7.0" }
rand = { version = "0.8.5" }
